# Generated by Django 6.0 on 2026-01-05 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kutaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lakk_kutaa', models.IntegerField(unique=True, verbose_name='Lakkoofsa Kutaa')),
                ('gaffii', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Barataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maqaa_guutuu', models.CharField(max_length=100)),
                ('bilbila_maatii', models.CharField(max_length=15)),
                ('maqaa_maatii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kutaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hordoffii.kutaa')),
            ],
        ),
        migrations.CreateModel(
            name='Hafittoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guyyaa', models.DateField()),
                ('jira', models.BooleanField(default=True)),
                ('barataa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hordoffii.barataa')),
            ],
        ),
        migrations.CreateModel(
            name='Qabxii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gosa_barumsaa', models.CharField(max_length=50)),
                ('qabxii_mid', models.FloatField(default=0)),
                ('qabxii_final', models.FloatField(default=0)),
                ('barataa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hordoffii.barataa')),
            ],
        ),
    ]
